[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.46.1"
gcollections = "1.5.0"
intervallum = "1.4.0"
itertools = "0.12.0"
lazy_static = "1.4.0"
regex = "1.10.2"
